import { ControlsSii } from "sii-parse-ts";

// eslint-disable-next-line
const _temp: ControlsSii = {
  SiiNunit: {
    input_config: [
      {
        id: "_nameless.230.be37.3680",
        version: 29,
        config_lines: [
          "device keyboard `sys.keyboard`",
          "device mouse `fusion.mouse`",
          "device joy ``",
          "device phys_mouse ``",
          "device joy2 ``",
          "device joy3 ``",
          "device joy4 ``",
          "device joy5 ``",
          "device joy6 ``",
          "device eye_track ``",
          "device ui_joy ``",
          "input j_steer `joy.x`",
          "input j_throttle `joy.rt`",
          "input j_brake `joy.lt`",
          "input j_clutch ``",
          "input j_look_ud `joy.ry`",
          "input j_look_lr `joy.rx`",
          "constant c_lr_dz 0.160000",
          "constant c_ud_dz 0.160000",
          "constant c_stm_simple 1.000000",
          "constant c_steer_func 0.000000",
          "constant c_steer_dz 0.160000",
          "constant c_throt_dz 0.100000",
          "constant c_brake_dz 0.100000",
          "constant c_clutch_dz 0.100000",
          "constant c_msens 0.330000",
          "constant c_minvert 0.000000",
          "constant c_jzthrottle 1.000000",
          "constant c_jithrottle 0.000000",
          "constant c_jzbrake 1.000000",
          "constant c_jibrake 0.000000",
          "constant c_jzclutch 0.000000",
          "constant c_jiclutch 0.000000",
          "constant c_jisteer 0.000000",
          "constant c_jilookud 0.000000",
          "constant c_jilooklr 0.000000",
          "constant c_rsteersens 1.000000",
          "constant c_asteersens 6.000000",
          "constant c_mousesteer 1.000000",
          "constant c_mousepedal 0.000000",
          "constant c_mped_dz 0.200000",
          "constant c_relatsteer 0.000000",
          "constant c_ff_enabled 0.000000",
          "constant c_ff_gain 5.000000",
          "constant c_ff_hi_spd 1.000000",
          "constant c_ff_lo_spd 0.500000",
          "constant c_ff_fricton 0.500000",
          "constant c_ff_engine 0.000000",
          "constant c_ff_surface 0.200000",
          "constant c_ff_bumps 1.000000",
          "constant c_ff_collis 1.000000",
          "constant c_ff_gearbox 0.320000",
          "constant c_ff_undrstr 0.500000",
          "constant c_ff_assist 0.500000",
          "constant c_vff_surfac 1.000000",
          "constant c_vff_bumps 1.000000",
          "constant c_vff_collis 1.000000",
          "constant c_atr_enable 1.000000",
          "constant c_atr_abs 1.000000",
          "constant c_atr_fail 1.000000",
          "constant c_atr_start 1.000000",
          "constant c_atr_wear 1.000000",
          "constant c_atr_brake 1.000000",
          "constant c_atr_clutch 1.000000",
          "constant c_krspeed 1.047198",
          "constant c_jrspeed 2.094395",
          "constant c_ht_on 1.000000",
          "constant c_ht_roll 0.000000",
          "constant c_et_head 1.000000",
          "constant c_et_pos 0.000000",
          "constant c_et_yawsc 1.000000",
          "constant c_et_pitchsc 1.000000",
          "constant c_et_rollsc 0.000000",
          "constant c_etwm_yawsc 1.000000",
          "constant c_etwm_pitsc 1.000000",
          "constant c_et_xscale 1.000000",
          "constant c_et_yscale 1.000000",
          "constant c_et_zscale 1.000000",
          "constant c_et_gv_res 0.500000",
          "constant c_et_hv_res 1.000000",
          "constant c_et_gv_ext 0.071389",
          "constant c_et_hv_dscy 0.750000",
          "constant c_et_hv_dscp 0.750000",
          "constant c_et_hv_dscr 1.000000",
          "constant c_et_hv_wscy 0.750000",
          "constant c_et_hv_wscp 0.750000",
          "constant c_et_hv_wscr 1.000000",
          "constant c_et_gv_exp 2.000000",
          "constant c_et_gv_inf 0.800000",
          "constant c_et_gv_sta 0.000000",
          "constant c_et_gv_end 1.000000",
          "constant c_et_hv_exp 1.000000",
          "constant c_et_hv_inf 0.510000",
          "constant c_et_hv_sta 0.020000",
          "constant c_et_hv_end 1.000000",
          "constant c_et_hv_ac 0.000000",
          "constant c_et_hv_mode 0.000000",
          "constant c_hsauto 0.000000",
          "mix any_shift `keyboard.lshift?0 | keyboard.rshift?0`",
          "mix any_ctrl `keyboard.lctrl?0 | keyboard.rctrl?0`",
          "mix any_alt `keyboard.lalt?0 | keyboard.ralt?0`",
          "mix any_cmd `keyboard.lcmd?0 | keyboard.rcmd?0`",
          "mix no_modifier `(! any_shift) & (! any_ctrl) & (! any_alt) & (! any_cmd)`",
          "mix shift_only `any_shift & (! any_ctrl) & (! any_alt) & (! any_cmd)`",
          "mix ctrl_only `any_ctrl & (! any_shift) & (! any_alt) & (! any_cmd)`",
          "mix alt_only `any_alt & (! any_shift) & (! any_ctrl) & (! any_cmd)`",
          "mix cmd_only `any_cmd & (! any_shift) & (! any_ctrl) & (! any_alt)`",
          "mix ctr_shf `any_ctrl & any_shift & (! any_alt) & (! any_cmd)`",
          "mix shf_alt `any_shift & any_alt & (! any_ctrl) & (! any_cmd)`",
          "mix ctr_alt `any_ctrl & any_alt & (! any_shift) & (! any_cmd)`",
          "mix ctr_shf_alt `any_ctrl & any_shift & any_alt & (! any_cmd)`",
          "mix cstm_mod_1 `unbound?0 | joy.lb?0`",
          "mix cstm_mod_2 ``",
          "mix cstm_mod_3 ``",
          "mix cstm_mod_4 ``",
          "mix cstm_mod_5 ``",
          "mix cstm_mod_6 ``",
          "mix no_cstm_mod `(! cstm_mod_1) & (! cstm_mod_2) & (! cstm_mod_3) & (! cstm_mod_4) & (! cstm_mod_5) & (! cstm_mod_6)`",
          "mix prv_itm `keyboard.uarrow?0`",
          "mix nxt_itm `keyboard.darrow?0`",
          "mix prv_ctrl `modifier(shift_only, keyboard.tab?0)`",
          "mix nxt_ctrl `modifier(no_modifier, keyboard.tab?0)`",
          "mix mve_left `keyboard.larrow?0`",
          "mix mve_right `keyboard.rarrow?0`",
          "mix mve_up `keyboard.uarrow?0`",
          "mix mve_down `keyboard.darrow?0`",
          "mix page_up `keyboard.pgup?0`",
          "mix page_down `keyboard.pgdn?0`",
          "mix j_left `ui_joy.j_left?0 | semantical.j_left?0`",
          "mix j_right `ui_joy.j_right?0 | semantical.j_right?0`",
          "mix j_up `ui_joy.j_up?0 | semantical.j_up?0`",
          "mix j_down `ui_joy.j_down?0 | semantical.j_down?0`",
          "mix selectfcs `keyboard.enter?0 | keyboard.numenter?0 | ui_joy.selectfcs?0 | semantical.selectfcs?0`",
          "mix back `keyboard.esc?0 | ui_joy.back?0 | semantical.back?0`",
          "mix skip `keyboard.esc?0 | ui_joy.skip?0 | semantical.skip?0`",
          "mix complete `modifier(no_modifier, keyboard.tab?0)`",
          "mix delete_p `modifier(no_modifier, keyboard.backspace?0)`",
          "mix delete_c `keyboard.del?0`",
          "mix line_sta `keyboard.home?0`",
          "mix line_end `keyboard.end?0`",
          "mix insert `modifier(no_modifier, keyboard.ins?0)`",
          "mix copy `modifier(ctrl_only, keyboard.c?0) || modifier(ctrl_only, keyboard.ins?0)`",
          "mix cut `modifier(ctrl_only, keyboard.x?0)`",
          "mix paste `modifier(ctrl_only, keyboard.v?0) || modifier(shift_only, keyboard.ins?0)`",
          "mix select_all `modifier(ctrl_only, keyboard.a?0)`",
          "mix select `mouse.button_left?0`",
          "mix selectalt `mouse.button_right?0`",
          "mix scrol_up `mouse.wheel_up?0 | semantical.scrol_up?0`",
          "mix scrol_dwn `mouse.wheel_down?0 | semantical.scrol_dwn?0`",
          "mix mapzoom_in `mouse.wheel_up?0 | semantical.mapzoom_in?0`",
          "mix mapzoom_out `mouse.wheel_down?0 | semantical.mapzoom_out?0`",
          "mix trs_zoom_in `mouse.wheel_up?0 | semantical.trs_zoom_in?0`",
          "mix trs_zoom_out `mouse.wheel_down?0 | semantical.trs_zoom_out?0`",
          "mix joy_nav_prv `ui_joy.joy_nav_prv?0 | semantical.joy_nav_prv?0`",
          "mix joy_nav_nxt `ui_joy.joy_nav_nxt?0 | semantical.joy_nav_nxt?0`",
          "mix joy_sec_prv `ui_joy.joy_sec_prv?0 | semantical.joy_sec_prv?0`",
          "mix joy_sec_nxt `ui_joy.joy_sec_nxt?0 | semantical.joy_sec_nxt?0`",
          "mix scroll_j_x `abs_max(ui_joy.scroll_j_x?0, semantical.scroll_j_x?0)`",
          "mix scroll_j_y `abs_max(ui_joy.scroll_j_y?0, semantical.scroll_j_y?0)`",
          "mix scroll_j_u `lte(scroll_j_y, -0.9)`",
          "mix scroll_j_d `gte(scroll_j_y, 0.9)`",
          "mix scroll_j_l `lte(scroll_j_x, -0.9)`",
          "mix scroll_j_r `gte(scroll_j_x, 0.9)`",
          "mix shortcut_1 `ui_joy.shortcut_1?0 | semantical.shortcut_1?0`",
          "mix shortcut_2 `ui_joy.shortcut_2?0 | semantical.shortcut_2?0`",
          "mix shortcut_3 `ui_joy.shortcut_3?0 | semantical.shortcut_3?0`",
          "mix shortcut_4 `ui_joy.shortcut_4?0 | semantical.shortcut_4?0`",
          "mix profmode `modifier(shift_only, keyboard.backspace?0)`",
          "mix imguitgl `modifier(shift_only, keyboard.grave?0)`",
          "mix console `modifier(no_modifier, keyboard.grave?0)`",
          "mix quit `modifier(alt_only, keyboard.f4?0)`",
          "mix pause `keyboard.pause?0 | semantical.pause?0`",
          "mix screenshot `keyboard.f10?0 | semantical.screenshot?0`",
          "mix dbgfovup `keyboard.numplus?0`",
          "mix dbgfovdown `keyboard.numminus?0`",
          "mix dbgfovreset `modifier(no_modifier, keyboard.nummultiply?0)`",
          "mix dbgcoltest `keyboard.numslash?0`",
          "mix dbgshowhud `keyboard.del?0`",
          "mix dbgchngpip `keyboard.ins?0`",
          "mix dbgnextmode `keyboard.num7?0`",
          "mix dbgdraw `keyboard.num1?0`",
          "mix dbglockpos `keyboard.num0?0`",
          "mix dbglockrot `keyboard.numperiod?0`",
          "mix dbgslowdwn `keyboard.pgdn?0`",
          "mix dbgspeedup `keyboard.pgup?0`",
          "mix dbgprev `keyboard.pgdn?0`",
          "mix dbgnext `keyboard.pgup?0`",
          "mix dbgstop `keyboard.home?0`",
          "mix dbgorbit `keyboard.numenter?0`",
          "mix dbgreset `keyboard.end?0`",
          "mix dbgrmvehic `keyboard.home?0`",
          "mix dbgmodcrea `keyboard.num0?0`",
          "mix dbgmodremo `keyboard.numperiod?0`",
          "mix dbgmodsele `keyboard.numenter?0`",
          "mix dbgnxcrty `keyboard.numslash?0`",
          "mix dbgcuracti `mouse.button_left?0`",
          "mix dbgchngsta `modifier(ctrl_only, mouse.button_middle?0)`",
          "mix dbgchngmod `modifier(ctrl_only, mouse.button_middle?0)`",
          "mix dbgselacti `mouse.button_right?0`",
          "mix dbgmacrost `keyboard.i?0`",
          "mix dbgmacrosa `keyboard.o?0`",
          "mix dbgmacrolo `keyboard.p?0`",
          "mix dbgfwd `keyboard.num8?0`",
          "mix dbgback `keyboard.num5?0`",
          "mix dbgleft `modifier(no_modifier, keyboard.num4?0)`",
          "mix dbgright `modifier(no_modifier, keyboard.num6?0)`",
          "mix dbgup `keyboard.num9?0`",
          "mix dbgdown `keyboard.num3?0`",
          "mix dbgrollleft `modifier(ctrl_only, keyboard.num4?0)`",
          "mix dbgrollright `modifier(ctrl_only, keyboard.num6?0)`",
          "mix dbgrollreset `modifier(ctrl_only, keyboard.nummultiply?0)`",
          "mix wndnext `keyboard.pgup?0`",
          "mix wndprev `keyboard.pgdn?0`",
          "mix j_look_lr_c `1`",
          "mix j_look_ud_c `no_cstm_mod?0`",
          "mix j_steer_c `1`",
          "mix j_throttle_c `1`",
          "mix j_brake_c `no_cstm_mod?0`",
          "mix j_clutch_c `1`",
          "mix sndedittool `keyboard.lshift?0 & keyboard.rshift?0`",
          "mix sndeditdata `keyboard.lalt?0 & keyboard.d?0`",
          "mix cam1 `keyboard.key1?0 || modifier(no_cstm_mod?0, long_press(joy.pov1_up?0)) | semantical.cam1?0`",
          "mix cam2 `keyboard.key2?0 | semantical.cam2?0`",
          "mix cam3 `keyboard.key3?0 | semantical.cam3?0`",
          "mix cam4 `keyboard.key4?0 | semantical.cam4?0`",
          "mix cam5 `keyboard.key5?0 | semantical.cam5?0`",
          "mix cam6 `keyboard.key6?0 | semantical.cam6?0`",
          "mix cam7 `keyboard.key7?0 | semantical.cam7?0`",
          "mix cam8 `keyboard.key8?0 | semantical.cam8?0`",
          "mix camcycle `keyboard.key9?0 || modifier(no_cstm_mod?0, short_press(joy.pov1_up?0)) | semantical.camcycle?0`",
          "mix camdbg `keyboard.key0?0`",
          "mix camwnd `keyboard.minus?0`",
          "mix camreset `unbound?0 || modifier(no_cstm_mod?0, short_press(joy.cancel?0)) | semantical.camreset?0`",
          "mix camrotate `mouse.button_right?0 | semantical.camrotate?0`",
          "mix camzoomin `mouse.wheel_up?0 | semantical.camzoomin?0`",
          "mix camzoomout `mouse.wheel_down?0 | semantical.camzoomout?0`",
          "mix camzoom `mouse.button_middle?0 || modifier(no_cstm_mod?0, joy.context4?0) | semantical.camzoom?0`",
          "mix camfwd `keyboard.num8?0 | semantical.camfwd?0`",
          "mix camback `keyboard.num5?0 | semantical.camback?0`",
          "mix camleft `keyboard.num4?0 | semantical.camleft?0`",
          "mix camright `keyboard.num6?0 | semantical.camright?0`",
          "mix camup `keyboard.num9?0 | semantical.camup?0`",
          "mix camdown `keyboard.num3?0 | semantical.camdown?0`",
          "mix cammove `mouse.button_right?0`",
          "mix lookleft `keyboard.numslash?0 | semantical.lookleft?0`",
          "mix lookright `keyboard.nummultiply?0 | semantical.lookright?0`",
          "mix camuilr `-mouse.rel_position.x?0 * c_msens`",
          "mix camuiud `-mouse.rel_position.y?0 * sel(c_minvert, -c_msens, c_msens)`",
          "mix camlr `-mouse.rel_position.x?0 * c_msens - semantical.camlr?0`",
          "mix camud `-mouse.rel_position.y?0 * sel(c_minvert, -c_msens, c_msens) - semantical.camud?0`",
          "mix j_cam_lk_lr `abs_max(ui_joy.j_cam_lk_lr?0, semantical.j_cam_lk_lr?0)`",
          "mix j_cam_lk_ud `abs_max(ui_joy.j_cam_lk_ud?0, semantical.j_cam_lk_ud?0)`",
          "mix j_cam_mv_lr `abs_max(ui_joy.j_cam_mv_lr?0, semantical.j_cam_mv_lr?0)`",
          "mix j_cam_mv_ud `abs_max(ui_joy.j_cam_mv_ud?0, semantical.j_cam_mv_ud?0)`",
          "mix j_trzoom_in `ui_joy.j_trzoom_in?0 | semantical.j_trzoom_in?0`",
          "mix j_trzoom_out `ui_joy.j_trzoom_out?0 | semantical.j_trzoom_out?0`",
          "mix j_mappan_x `abs_max(ui_joy.j_mappan_x?0, semantical.j_mappan_x?0)`",
          "mix j_mappan_y `abs_max(ui_joy.j_mappan_y?0, semantical.j_mappan_y?0)`",
          "mix j_mapzom_in `ui_joy.j_mapzom_in?0 | semantical.j_mapzom_in?0`",
          "mix j_mapzom_out `ui_joy.j_mapzom_out?0 | semantical.j_mapzom_out?0`",
          "mix looklranaraw `memory(j_look_lr_c?1, deadzone(-sel(c_jilooklr, -j_look_lr?0, j_look_lr?0), c_lr_dz))`",
          "mix lookudanaraw `memory(j_look_ud_c?1, deadzone(-sel(c_jilookud, -j_look_ud?0, j_look_ud?0), c_ud_dz))`",
          "mix looklrdigspd `(bool(lookleft) - bool(lookright)) * c_krspeed`",
          "mix looklranaspd `looklranaraw * c_jrspeed`",
          "mix looklrspd `looklrdigspd + looklranaspd`",
          "mix lookudspd `lookudanaraw * c_jrspeed`",
          "mix lookpos1 `keyboard.num5?0 | semantical.lookpos1?0`",
          "mix lookpos2 `keyboard.num9?0 | semantical.lookpos2?0`",
          "mix lookpos3 `keyboard.num7?0 | semantical.lookpos3?0`",
          "mix lookpos4 `keyboard.num6?0 | semantical.lookpos4?0`",
          "mix lookpos5 `keyboard.num4?0 | semantical.lookpos5?0`",
          "mix lookpos6 `keyboard.num8?0 | semantical.lookpos6?0`",
          "mix lookpos7 `semantical.lookpos7?0`",
          "mix lookpos8 `semantical.lookpos8?0`",
          "mix lookpos9 `semantical.lookpos9?0`",
          "mix looksteer `semantical.looksteer?0`",
          "mix lookblink `semantical.lookblink?0`",
          "mix trackiron `trackir.device.active?0`",
          "mix trackiryaw `trackir.device.position.yaw?0`",
          "mix trackirpitch `trackir.device.position.pitch?0`",
          "mix trackirroll `trackir.device.position.roll?0`",
          "mix trackirx `trackir.device.position.x?0`",
          "mix trackiry `trackir.device.position.y?0`",
          "mix trackirz `trackir.device.position.z?0`",
          "mix hmdon `hmd.device.active?0`",
          "mix hmdyaw `hmd.device.position.yaw?0`",
          "mix hmdpitch `hmd.device.position.pitch?0`",
          "mix hmdroll `hmd.device.position.roll?0`",
          "mix hmdx `hmd.device.position.x?0`",
          "mix hmdy `hmd.device.position.y?0`",
          "mix hmdz `hmd.device.position.z?0`",
          "mix eyepresenton `eye_track.user_present_valid?0`",
          "mix eyepresent `eye_track.user_present?0`",
          "mix eyegazeon `eye_track.gaze_position_valid?0`",
          "mix eyegazex `eye_track.gaze_position.x?0`",
          "mix eyegazey `eye_track.gaze_position.y?0`",
          "mix eyeposon `c_et_head & eye_track.head_position_valid?0`",
          "mix eyeposyaw `eye_track.head_position.yaw?0 * c_et_yawsc`",
          "mix eyepospitch `eye_track.head_position.pitch?0 * c_et_pitchsc`",
          "mix eyeposroll `eye_track.head_position.roll?0 * c_et_rollsc`",
          "mix eyeposx `sel(c_et_pos, eye_track.head_position.x?0 * c_et_xscale, 0)`",
          "mix eyeposy `sel(c_et_pos, eye_track.head_position.y?0 * c_et_yscale, 0)`",
          "mix eyeposz `sel(c_et_pos, eye_track.head_position.z?0 * c_et_zscale, 0)`",
          "mix eyeposwmyaw `eye_track.head_position.yaw?0 * c_etwm_yawsc`",
          "mix eyeposwmpitc `eye_track.head_position.pitch?0 * c_etwm_pitsc`",
          "mix eyeposwmroll `eye_track.head_position.roll?0 * c_et_rollsc`",
          "mix eyeposwmx `sel(c_et_pos, eye_track.head_position.x?0 * c_et_xscale, 0)`",
          "mix eyeposwmy `sel(c_et_pos, eye_track.head_position.y?0 * c_et_yscale, 0)`",
          "mix eyeposwmz `sel(c_et_pos, eye_track.head_position.z?0 * c_et_zscale, 0)`",
          "mix headtron `c_ht_on & (trackiron | hmdon | eyeposon)`",
          "mix headtryaw `sel(trackiron, trackiryaw, 0) + sel(hmdon, hmdyaw, 0) + sel(eyeposon, eyeposyaw, 0)`",
          "mix headtrpitch `sel(trackiron, trackirpitch, 0) + sel(hmdon, hmdpitch, 0) + sel(eyeposon, eyepospitch, 0)`",
          "mix headtrroll `sel(trackiron & c_ht_roll, trackirroll, 0) + sel(hmdon, hmdroll, 0) + sel(eyeposon, eyeposroll, 0)`",
          "mix headtrx `clamp(sel(trackiron, trackirx, 0) + sel(eyeposon, eyeposx, 0), -0.1, 0.1) + sel(hmdon, hmdx, 0)`",
          "mix headtry `clamp(sel(trackiron, trackiry, 0) + sel(eyeposon, eyeposy, 0), -0.05, 0.05) + sel(hmdon, hmdy, 0)`",
          "mix headtrz `clamp(sel(trackiron, trackirz, 0) + sel(eyeposon, eyeposz, 0), -0.2, 0.05) + sel(hmdon, hmdz, 0)`",
          "mix headtrwmon `c_ht_on & (trackiron | hmdon | eyeposon)`",
          "mix headtrwmyaw `sel(trackiron, trackiryaw, 0) + sel(hmdon, hmdyaw, 0) + sel(eyeposon, eyeposwmyaw, 0)`",
          "mix headtrwmpitc `sel(trackiron, trackirpitch, 0) + sel(hmdon, hmdpitch, 0) + sel(eyeposon, eyeposwmpitc, 0)`",
          "mix headtrwmroll `sel(trackiron & c_ht_roll, trackirroll, 0) + sel(hmdon, hmdroll, 0) + sel(eyeposon, eyeposwmroll, 0)`",
          "mix headtrwmx `clamp(sel(trackiron, trackirx, 0) + sel(eyeposon, eyeposwmx, 0), -0.1, 0.1) + sel(hmdon, hmdx, 0)`",
          "mix headtrwmy `clamp(sel(trackiron, trackiry, 0) + sel(eyeposon, eyeposwmy, 0), -0.1, 0.1) + sel(hmdon, hmdy, 0)`",
          "mix headtrwmz `clamp(sel(trackiron, trackirz, 0) + sel(eyeposon, eyeposwmz, 0), -0.1, 0.1) + sel(hmdon, hmdz, 0)`",
          "mix dsteerleft `keyboard.larrow?0 | keyboard.a?0`",
          "mix dsteerright `keyboard.rarrow?0 | keyboard.d?0`",
          "mix dsteering `dsteerleft - dsteerright`",
          "mix steering `dsteering - memory(j_steer_c?1, (pow(normalize(abs(sel(c_jisteer, -j_steer?0, j_steer?0)), c_steer_dz), (1.0 + c_steer_func * 0.5)) * sign(sel(c_jisteer, -j_steer?0, j_steer?0)))) - semantical.steering?0`",
          "mix msteering `-mouse.rel_position.x?0 * c_msens`",
          "mix mpedals `-mouse.rel_position.y?0 * c_msens`",
          "mix dforward `keyboard.uarrow?0 | keyboard.w?0`",
          "mix dbackward `keyboard.darrow?0 | keyboard.s?0`",
          "mix aforward `memory(j_throttle_c?1, normalize(sel(c_jzthrottle, sel(c_jithrottle, -j_throttle?0, j_throttle?0), sel(c_jithrottle, j_throttle?1 * -0.5 + 0.5, j_throttle?-1 * 0.5 + 0.5)), c_throt_dz)) + semantical.aforward?0`",
          "mix abackward `memory(j_brake_c?1, normalize(sel(c_jzbrake, sel(c_jibrake, -j_brake?0, j_brake?0), sel(c_jibrake, j_brake?1 * -0.5 + 0.5, j_brake?-1 * 0.5 + 0.5)), c_brake_dz)) + semantical.abackward?0`",
          "mix forward `dforward + aforward`",
          "mix backward `dbackward + abackward`",
          "mix dclutch ``",
          "mix clutch `dclutch + memory(j_clutch_c?1, normalize(sel(c_jzclutch, sel(c_jiclutch, -j_clutch?0, j_clutch?0), sel(c_jiclutch, j_clutch?1 * -0.5 + 0.5, j_clutch?-1 * 0.5 + 0.5)), c_clutch_dz)) + semantical.clutch?0`",
          "mix activate `keyboard.enter?0 || modifier(no_cstm_mod?0, joy.accept?0) | semantical.activate?0`",
          "mix menu `keyboard.esc?0 || short_press(joy.menu1?0) | semantical.menu?0`",
          "mix engine `keyboard.e?0 || modifier(no_cstm_mod?0, long_press(joy.pov1_right?0)) | semantical.engine?0`",
          "mix engineelect `semantical.engineelect?0`",
          "mix ignitionoff `semantical.ignitionoff?0`",
          "mix ignitionon `semantical.ignitionon?0`",
          "mix ignitionstrt `semantical.ignitionstrt?0`",
          "mix attach `keyboard.t?0 || modifier(no_cstm_mod?0, long_press(joy.pov1_left?0)) | semantical.attach?0`",
          "mix frontsuspup `semantical.frontsuspup?0`",
          "mix frontsuspdwn `semantical.frontsuspdwn?0`",
          "mix rearsuspup `semantical.rearsuspup?0`",
          "mix rearsuspdwn `semantical.rearsuspdwn?0`",
          "mix suspreset `semantical.suspreset?0`",
          "mix horn `keyboard.h?0 || modifier(no_cstm_mod?0, joy.context3?0) | semantical.horn?0`",
          "mix airhorn `keyboard.n?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), joy.context3?0) | semantical.airhorn?0`",
          "mix lighthorn `keyboard.j?0 | semantical.lighthorn?0`",
          "mix beacon `keyboard.o?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), joy.context1?0) | semantical.beacon?0`",
          "mix motorbrake `keyboard.b?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), derived(joy.button_lt?0, joy.lt)) | semantical.motorbrake?0`",
          "mix engbraketog `semantical.engbraketog?0`",
          "mix engbrakeup `semantical.engbrakeup?0`",
          "mix engbrakedwn `semantical.engbrakedwn?0`",
          "mix trailerbrake `keyboard.bslash?0 | semantical.trailerbrake?0`",
          "mix retarderup `keyboard.semicolon?0 | semantical.retarderup?0`",
          "mix retarderdown `keyboard.apostrophe?0 | semantical.retarderdown?0`",
          "mix retarder0 `semantical.retarder0?0`",
          "mix retarder1 `semantical.retarder1?0`",
          "mix retarder2 `semantical.retarder2?0`",
          "mix retarder3 `semantical.retarder3?0`",
          "mix retarder4 `semantical.retarder4?0`",
          "mix retarder5 `semantical.retarder5?0`",
          "mix liftaxle `keyboard.u?0 | semantical.liftaxle?0`",
          "mix liftaxlet `semantical.liftaxlet?0`",
          "mix slideaxlefwd `semantical.slideaxlefwd?0`",
          "mix slideaxlebwd `semantical.slideaxlebwd?0`",
          "mix slideaxleman `semantical.slideaxleman?0`",
          "mix trlrsuspup `semantical.trlrsuspup?0`",
          "mix trlrsuspdwn `semantical.trlrsuspdwn?0`",
          "mix diflock `keyboard.v?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), joy.pov1_right?0) | semantical.diflock?0`",
          "mix rwinopen `semantical.rwinopen?0`",
          "mix rwinclose `semantical.rwinclose?0`",
          "mix lwinopen `semantical.lwinopen?0`",
          "mix lwinclose `semantical.lwinclose?0`",
          "mix engbrakeauto `semantical.engbrakeauto?0`",
          "mix retarderauto `semantical.retarderauto?0`",
          "mix embrake `unbound?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), joy.pov1_down?0) | semantical.embrake?0`",
          "mix laneassmode `unbound?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), long_press(joy.pov1_up?0)) | semantical.laneassmode?0`",
          "mix tranpwrmode `semantical.tranpwrmode?0`",
          "mix parkingbrake `keyboard.space?0 || modifier(no_cstm_mod?0, long_press(joy.pov1_down?0)) | semantical.parkingbrake?0`",
          "mix wipers `keyboard.p?0 || modifier(no_cstm_mod?0, short_press(joy.pov1_down?0)) | semantical.wipers?0`",
          "mix wipersback `semantical.wipersback?0`",
          "mix wipers0 `semantical.wipers0?0`",
          "mix wipers1 `semantical.wipers1?0`",
          "mix wipers2 `semantical.wipers2?0`",
          "mix wipers3 `semantical.wipers3?0`",
          "mix wipers4 `semantical.wipers4?0`",
          "mix cruiectrl `keyboard.c?0 || modifier(no_cstm_mod?0, long_press(joy.cancel?0)) | semantical.cruiectrl?0`",
          "mix cruiectrlinc `keyboard.numplus?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), joy.context2?0) | semantical.cruiectrlinc?0`",
          "mix cruiectrldec `keyboard.numminus?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), joy.accept?0) | semantical.cruiectrldec?0`",
          "mix cruiectrlres `unbound?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), short_press(joy.cancel?0)) | semantical.cruiectrlres?0`",
          "mix accmode `unbound?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), long_press(joy.cancel?0)) | semantical.accmode?0`",
          "mix laneassist `keyboard.minus?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), short_press(joy.pov1_up?0)) | semantical.laneassist?0`",
          "mix light `keyboard.l?0 || modifier(no_cstm_mod?0, short_press(joy.context1?0)) | semantical.light?0`",
          "mix lightoff `semantical.lightoff?0`",
          "mix lightpark `semantical.lightpark?0`",
          "mix lighton `semantical.lighton?0`",
          "mix hblight `keyboard.k?0 || modifier(no_cstm_mod?0, long_press(joy.context1?0)) | semantical.hblight?0`",
          "mix lblinker `keyboard.lbracket?0 || modifier(no_cstm_mod?0, short_press(joy.pov1_left?0)) | semantical.lblinker?0`",
          "mix lblinkerh `semantical.lblinkerh?0`",
          "mix rblinker `keyboard.rbracket?0 || modifier(no_cstm_mod?0, short_press(joy.pov1_right?0)) | semantical.rblinker?0`",
          "mix rblinkerh `semantical.rblinkerh?0`",
          "mix flasher4way `keyboard.f?0 || modifier(no_cstm_mod?0, long_press(joy.menu2?0)) | semantical.flasher4way?0`",
          "mix showmirrors `keyboard.f2?0 | semantical.showmirrors?0`",
          "mix showhud `keyboard.f3?0 | semantical.showhud?0`",
          "mix navmap `keyboard.m?0 || modifier(no_cstm_mod?0, short_press(joy.menu2?0)) | semantical.navmap?0`",
          "mix photo_mode `keyboard.equal?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), joy.menu2?0) | semantical.photo_mode?0`",
          "mix quicksave `keyboard.scrollock?0 | semantical.quicksave?0`",
          "mix quickload `semantical.quickload?0`",
          "mix acaquickr `semantical.acaquickr?0`",
          "mix radio `semantical.radio?0`",
          "mix radionext `semantical.radionext?0`",
          "mix radioprev `semantical.radioprev?0`",
          "mix radioup `semantical.radioup?0`",
          "mix radiodown `semantical.radiodown?0`",
          "mix display `keyboard.i?0 | semantical.display?0`",
          "mix quickpark `keyboard.q?0 | semantical.quickpark?0`",
          "mix dashmapzoom `semantical.dashmapzoom?0`",
          "mix tripreset `semantical.tripreset?0`",
          "mix eyecfg `modifier(shift_only, keyboard.numlock?0)`",
          "mix sb_activate `keyboard.tab?0 | semantical.sb_activate?0`",
          "mix sb_swap `keyboard.caps?0 | semantical.sb_swap?0`",
          "mix infotainment `semantical.infotainment?0`",
          "mix mapcenter `keyboard.f?0 | semantical.mapcenter?0`",
          "mix photores `keyboard.r?0 | ui_joy.photores?0 | semantical.photores?0`",
          "mix photomove `mouse.button_right?0 | semantical.photomove?0`",
          "mix phototake `mouse.button_left?0 | semantical.phototake?0`",
          "mix photofwd `keyboard.w?0 | semantical.photofwd?0`",
          "mix photobwd `keyboard.s?0 | semantical.photobwd?0`",
          "mix photoleft `keyboard.a?0 | semantical.photoleft?0`",
          "mix photoright `keyboard.d?0 | semantical.photoright?0`",
          "mix photoup `keyboard.q?0 | ui_joy.photoup?0 | semantical.photoup?0`",
          "mix photodown `keyboard.e?0 | ui_joy.photodown?0 | semantical.photodown?0`",
          "mix photorolll `keyboard.z?0 | semantical.photorolll?0`",
          "mix photorollr `keyboard.c?0 | semantical.photorollr?0`",
          "mix photosman `keyboard.m?0 | ui_joy.photosman?0 | semantical.photosman?0`",
          "mix photo_opts `keyboard.space?0 | ui_joy.photo_opts?0 | semantical.photo_opts?0`",
          "mix photosnap `keyboard.enter?0 | ui_joy.photosnap?0 | semantical.photosnap?0`",
          "mix photo_hctrl `keyboard.h?0 | ui_joy.photo_hctrl?0 | semantical.photo_hctrl?0`",
          "mix photonames `keyboard.n?0 | semantical.photonames?0`",
          "mix photozoomout `mouse.wheel_down?0 | semantical.photozoomout?0`",
          "mix photozoomin `mouse.wheel_up?0 | semantical.photozoomin?0`",
          "mix phot_z_j_out `ui_joy.phot_z_j_out?0 | semantical.phot_z_j_out?0`",
          "mix phot_z_j_in `ui_joy.phot_z_j_in?0 | semantical.phot_z_j_in?0`",
          "mix album_pgup `keyboard.pgup?0 | semantical.album_pgup?0`",
          "mix album_pgdn `keyboard.pgdn?0 | semantical.album_pgdn?0`",
          "mix album_itup `keyboard.uarrow?0 | semantical.album_itup?0`",
          "mix album_itdn `keyboard.darrow?0 | semantical.album_itdn?0`",
          "mix album_itlf `keyboard.larrow?0 | semantical.album_itlf?0`",
          "mix album_itrg `keyboard.rarrow?0 | semantical.album_itrg?0`",
          "mix album_ithm `keyboard.home?0 | semantical.album_ithm?0`",
          "mix album_iten `keyboard.end?0 | semantical.album_iten?0`",
          "mix album_itac `keyboard.enter?0 | keyboard.numenter?0 | semantical.album_itac?0`",
          "mix album_itop `keyboard.space?0 | semantical.album_itop?0`",
          "mix album_itdl `keyboard.del?0 | semantical.album_itdl?0`",
          "mix camwalk_for `keyboard.w?0 | semantical.camwalk_for?0`",
          "mix camwalk_back `keyboard.s?0 | semantical.camwalk_back?0`",
          "mix camwalk_righ `keyboard.d?0 | semantical.camwalk_righ?0`",
          "mix camwalk_left `keyboard.a?0 | semantical.camwalk_left?0`",
          "mix camwalk_run `keyboard.lshift?0 | semantical.camwalk_run?0`",
          "mix camwalk_jump `keyboard.space?0 | semantical.camwalk_jump?0`",
          "mix camwalk_crou `keyboard.lctrl?0 | ui_joy.camwalk_crou?0 | semantical.camwalk_crou?0`",
          "mix camwalk_lr `-semantical.camwalk_lr?0`",
          "mix camwalk_ud `-semantical.camwalk_ud?0`",
          "mix camwalk_lrs `looklranaraw * c_jrspeed`",
          "mix camwalk_uds `lookudanaraw * c_jrspeed`",
          "mix gearup `keyboard.lshift?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), derived(joy.rstick_up?0, joy.ry)) | semantical.gearup?0`",
          "mix geardown `keyboard.lctrl?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), derived(joy.rstick_down?0, joy.ry)) | semantical.geardown?0`",
          "mix gear0 `unbound?0 || modifier(cstm_mod_1?0 & (! cstm_mod_2?0) & (! cstm_mod_3?0) & (! cstm_mod_4?0) & (! cstm_mod_5?0) & (! cstm_mod_6?0), long_press(joy.context4?0)) | semantical.gear0?0`",
          "mix geardrive `semantical.geardrive?0`",
          "mix gearreverse `semantical.gearreverse?0`",
          "mix gearuphint `semantical.gearuphint?0`",
          "mix geardownhint `semantical.geardownhint?0`",
          "mix transemi `semantical.transemi?0`",
          "mix drive `semantical.drive?0`",
          "mix reverse `semantical.reverse?0`",
          "mix cmirrorsel `semantical.cmirrorsel?0`",
          "mix fmirrorsel `semantical.fmirrorsel?0`",
          "mix mirroryawl `semantical.mirroryawl?0`",
          "mix mirroryawr `semantical.mirroryawr?0`",
          "mix mirrorpitu `semantical.mirrorpitu?0`",
          "mix mirrorpitl `semantical.mirrorpitl?0`",
          "mix mirrorreset `semantical.mirrorreset?0`",
          "mix quicksel1 `keyboard.key1?0 | keyboard.num1?0 | semantical.quicksel1?0`",
          "mix quicksel2 `keyboard.key2?0 | keyboard.num2?0 | semantical.quicksel2?0`",
          "mix quicksel3 `keyboard.key3?0 | keyboard.num3?0 | semantical.quicksel3?0`",
          "mix quicksel4 `keyboard.key4?0 | keyboard.num4?0 | semantical.quicksel4?0`",
          "mix quicksel5 `keyboard.key5?0 | keyboard.num5?0 | semantical.quicksel5?0`",
          "mix quicksel6 `keyboard.key6?0 | keyboard.num6?0 | semantical.quicksel6?0`",
          "mix quicksel7 `keyboard.key7?0 | keyboard.num7?0 | semantical.quicksel7?0`",
          "mix quicksel8 `keyboard.key8?0 | keyboard.num8?0 | semantical.quicksel8?0`",
          "mix mpptt `keyboard.x?0 | semantical.mpptt?0`",
          "mix replayhidec `keyboard.h?0 | semantical.replayhidec?0`",
          "mix teleport `modifier(ctrl_only, keyboard.f9?0)`",
          "mix bugreportrec `modifier(no_modifier, keyboard.f11?0)`",
          "mix bugrepscrrcc `modifier(shift_only, keyboard.f11?0)`",
          "mix bugreportshw `modifier(ctrl_only, keyboard.f11?0)`",
          "mix camsave_rec `modifier(alt_only, keyboard.f12?0)`",
          "mix camsave_next `modifier(ctrl_only, keyboard.f12?0)`",
          "mix camsave_prev `modifier(ctr_shf, keyboard.f12?0)`",
          "mix recordonoff `modifier(no_modifier, keyboard.z?0)`",
          "mix replayonoff `modifier(alt_only, keyboard.z?0)`",
          "mix replayplype `keyboard.darrow?0`",
          "mix replaystop `keyboard.uarrow?0`",
          "mix replayff `keyboard.rarrow?0`",
          "mix replayback `keyboard.larrow?0`",
          "mix repcamup `keyboard.w?0`",
          "mix repcamdown `keyboard.s?0`",
          "mix repcamleft `keyboard.a?0`",
          "mix repcamright `keyboard.d?0`",
          "mix repcamrolll `keyboard.q?0`",
          "mix repcamrollr `keyboard.e?0`",
          "mix repcamlock `keyboard.r?0`",
          "mix repcamorbitt `keyboard.pgup?0`",
          "mix repcamorbite `keyboard.pgdn?0`",
          "mix gearsel1on `semantical.gearsel1on?0`",
          "mix gearsel1off `semantical.gearsel1off?0`",
          "mix gearsel1tgl `semantical.gearsel1tgl?0`",
          "mix gearsel2on `semantical.gearsel2on?0`",
          "mix gearsel2off `semantical.gearsel2off?0`",
          "mix gearsel2tgl `semantical.gearsel2tgl?0`",
          "mix gear1 `joy.b15?0 | semantical.gear1?0`",
          "mix gear2 `joy.b9?0 | semantical.gear2?0`",
          "mix gear3 `joy.b10?0 | semantical.gear3?0`",
          "mix gear4 `joy.b11?0 | semantical.gear4?0`",
          "mix gear5 `joy.b12?0 | semantical.gear5?0`",
          "mix gear6 `joy.b13?0 | semantical.gear6?0`",
          "mix gear7 `joy.b14?0 | semantical.gear7?0`",
          "mix gear8 `semantical.gear8?0`",
          "mix gear9 `semantical.gear9?0`",
          "mix gear10 `semantical.gear10?0`",
          "mix gear11 `semantical.gear11?0`",
          "mix gear12 `semantical.gear12?0`",
          "mix gear13 `semantical.gear13?0`",
          "mix gear14 `semantical.gear14?0`",
          "mix gear15 `semantical.gear15?0`",
          "mix gear16 `semantical.gear16?0`",
          "mix adjuster `keyboard.f4?0 | semantical.adjuster?0`",
          "mix advpage0 `keyboard.f5?0 || modifier(no_cstm_mod?0, long_press(joy.context2?0)) | semantical.advpage0?0`",
          "mix advpage1 `keyboard.f6?0 | semantical.advpage1?0`",
          "mix advpage2 `keyboard.f7?0 | semantical.advpage2?0`",
          "mix advpage3 `keyboard.f8?0 | semantical.advpage3?0`",
          "mix advpage4 `keyboard.f9?0 | semantical.advpage4?0`",
          "mix advpagen `keyboard.num0?0 || modifier(no_cstm_mod?0, short_press(joy.context2?0)) | semantical.advpagen?0`",
          "mix advpagep `semantical.advpagep?0`",
          "mix advmouse `keyboard.f1?0 || long_press(joy.menu1?0) | semantical.advmouse?0`",
          "mix advetamode `semantical.advetamode?0`",
          "mix gar_man `keyboard.g?0 | semantical.gar_man?0`",
          "mix advzoomin `semantical.advzoomin?0`",
          "mix advzoomout `semantical.advzoomout?0`",
          "mix demo_restart ``",
          "mix demo_setday ``",
          "mix demo_setnght ``",
          "mix demo_setrain ``",
          "mix demo_setsun ``",
          "mix demo_trfon ``",
          "mix demo_trfoff ``",
          "mix assistact1 `keyboard.key1?0 | semantical.assistact1?0`",
          "mix assistact2 `keyboard.key2?0 | semantical.assistact2?0`",
          "mix assistact3 `keyboard.key3?0 | semantical.assistact3?0`",
          "mix assistact4 `keyboard.key4?0 | semantical.assistact4?0`",
          "mix assistact5 `keyboard.key5?0 | semantical.assistact5?0`",
          "mix adj_seats `keyboard.key1?0 | semantical.adj_seats?0`",
          "mix adj_mirrors `keyboard.key2?0 | semantical.adj_mirrors?0`",
          "mix adj_lights `keyboard.key3?0 | semantical.adj_lights?0`",
          "mix adj_uimirror `keyboard.key4?0 | semantical.adj_uimirror?0`",
          "mix chat_act `keyboard.y?0 | semantical.chat_act?0`",
          "mix quick_chat `keyboard.q?0 | semantical.quick_chat?0`",
          "mix cycl_zoom `keyboard.tab?0 | semantical.cycl_zoom?0`",
          "mix name_tags `keyboard.z?0 | semantical.name_tags?0`",
          "mix headreset `keyboard.f12?0 | semantical.headreset?0`",
          "mix headtren ``",
          "mix menustereo `keyboard.f11?0 | semantical.menustereo?0`",
          "mix eyepause ``",
          "mix eyepreset1 ``",
          "mix eyepreset2 ``",
          "mix eyepreset3 ``",
          "mix eyepreset4 ``",
          "mix eyepreset5 ``",
        ],
      },
    ],
  },
};
